name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@8e737bb29a1e25361a0326c0cd68d247a2978e5 # v6.1.0
        with:
          python-version: "3.11"
      - run: python3 -m py_compile main.py
